---
- name: Install citus yum repository
  yum_repository:
    name: citusdata_community
    state: present
    baseurl: https://packagecloud.io/citusdata/community/el/7/$basearch
    description: citusdata_community
    repo_gpgcheck: false
    gpgcheck: false
    enabled: true
    gpgkey: https://packagecloud.io/citusdata/community/gpgkey
    sslverify: true
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: 300

- name: Install postgresql yum repository
  package:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
